### ISSUE TITLE
Installing with `make run` fails

### ISSUE THREAD

**Issue by arokem** [cesium-ml/baselayer#29]
```
chlosyne:baselayer (master) $make run
[·] Silently executing: pip install -r requirements.txt
[✓] Silently executing: pip install -r requirements.txt
[✗] Silently executing: pip install -r ../requirements.txt

! Failure (exit code 1).
--- stdout ---
Could not open requirements file: [Errno 2] No such file or directory: '../requirements.txt'
--- end ---
make: *** [dependencies] Error 1
```

**Comment by stefanv** [comment]
@arokem I'll make this clearer in the docs, but baselayer is a submodule used by other apps.

Can you try the same with https://github.com/cesium-ml/baselayer_template_app ?  Thank you!

**Comment by arokem** [comment]
Ah! Gotcha. 

This requires 3.6? 

```
chlosyne:baselayer  $make run
[✓] Silently executing: pip install -r requirements.txt
[✓] Silently executing: pip install -r ../requirements.txt
[✓] Silently executing: baselayer/tools/check_js_deps.sh
pip install -q pyyaml
find . -name "*.template" | PYTHONPATH=.. xargs ./tools/fill_conf_values.py
Traceback (most recent call last):
  File "./tools/fill_conf_values.py", line 6, in <module>
    from baselayer.app.env import load_env
  File "/Users/arokem/source/baselayer_template_app/baselayer/app/env.py", line 7, in <module>
    from .config import load_config
  File "/Users/arokem/source/baselayer_template_app/baselayer/app/config.py", line 37
    print(f'[baselayer] Loaded {relpath}')
                                        ^
SyntaxError: invalid syntax
make: *** [fill_conf_values] Error 1
```

**Comment by stefanv** [comment]
Oh, yes :)  Maybe I should mention that!

**Comment by stefanv** [comment]
I've updated Baselayer to

1) guard against the error you ran into (it now warns when it does not detect an app surrounding it
2) check all the basic system requirements (npm, supervisord, nginx, etc.)

I hope that helps!
